CREATE TABLE IF NOT EXISTS ratings (
    id SERIAL PRIMARY KEY,
    movie_id INTEGER NOT NULL FOREIGN KEY REFERENCES movies(id),
    user_id INTEGER NOT NULL FOREIGN KEY REFERENCES users(id),
    score INTEGER NOT NULL (score BETWEEN 1 AND 5),
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);